<a href="https://colab.research.google.com/github/baiiraam/baiiraam/blob/main/Numerical_Dataset_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
diabetes = pd.read_csv('/content/diabetes.csv')

In [3]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35  ...  33.6                     0.627   50        1
1            1       85             66             29  ...  26.6                     0.351   31        0
2            8      183             64              0  ...  23.3                     0.672   32        1
3            1       89             66             23  ...  28.1                     0.167   21        0
4            0      137             40             35  ...  43.1                     2.288   33        1

[5 rows x 9 columns]

In [4]:
diabetes.shape

(768, 9)

In [5]:
diabetes.describe()

Pregnancies     Glucose  BloodPressure  ...  DiabetesPedigreeFunction         Age     Outcome
count   768.000000  768.000000     768.000000  ...                768.000000  768.000000  768.000000
mean      3.845052  120.894531      69.105469  ...                  0.471876   33.240885    0.348958
std       3.369578   31.972618      19.355807  ...                  0.331329   11.760232    0.476951
min       0.000000    0.000000       0.000000  ...                  0.078000   21.000000    0.000000
25%       1.000000   99.000000      62.000000  ...                  0.243750   24.000000    0.000000
50%       3.000000  117.000000      72.000000  ...                  0.372500   29.000000    0.000000
75%       6.000000  140.250000      80.000000  ...                  0.626250   41.000000    1.000000
max      17.000000  199.000000     122.000000  ...                  2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [6]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
diabetes.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
X = diabetes.drop("Outcome", axis=1)
y = diabetes["Outcome"]

X, y

(     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
 0              6      148             72  ...  33.6                     0.627   50
 1              1       85             66  ...  26.6                     0.351   31
 2              8      183             64  ...  23.3                     0.672   32
 3              1       89             66  ...  28.1                     0.167   21
 4              0      137             40  ...  43.1                     2.288   33
 ..           ...      ...            ...  ...   ...                       ...  ...
 763           10      101             76  ...  32.9                     0.171   63
 764            2      122             70  ...  36.8                     0.340   27
 765            5      121             72  ...  26.2                     0.245   30
 766            1      126             60  ...  30.1                     0.349   47
 767            1       93             70  ...  30.4                     0.3

In [9]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
diabetes["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [12]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in sss.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

X_scaled = scaler.transform(X_train)
X_scaled

array([[-0.84488505, -0.96691063, -0.36733675, ..., -0.6082704 ,
         0.3265464 , -0.78628618],
       [ 0.3429808 ,  0.1597866 ,  0.45982725, ..., -0.30366421,
        -0.09929033,  0.57511787],
       [-0.54791859, -0.49745345, -0.57412775, ...,  0.36900779,
        -0.74559573, -0.70119842],
       ...,
       [-0.84488505, -0.74783062,  0.04624525, ...,  0.77514938,
        -0.76673656, -0.27575966],
       [ 1.82781311, -0.30967058,  0.04624525, ..., -0.57019463,
        -0.9992857 ,  0.57511787],
       [ 0.04601433,  0.72313521, -0.57412775, ..., -0.31635613,
        -0.55834837,  0.31985461]])

In [15]:
svm_clf = SVC()

svm_clf.fit(X_scaled, y_train)
y_pred = svm_clf.predict(X_scaled)

acc_sc_1 = accuracy_score(y_train, y_pred)
conf_mx = confusion_matrix(y_train, y_pred)
cl_rp_1 = classification_report(y_train, y_pred)

print(acc_sc_1)
print(conf_mx)
print(cl_rp_1)


0.8355048859934854
[[371  29]
 [ 72 142]]
              precision    recall  f1-score   support

           0       0.84      0.93      0.88       400
           1       0.83      0.66      0.74       214

    accuracy                           0.84       614
   macro avg       0.83      0.80      0.81       614
weighted avg       0.84      0.84      0.83       614



In [16]:
X_scaled_test = scaler.transform(X_test)
y_pred_test = svm_clf.predict(X_scaled_test)

acc_sc_2 = accuracy_score(y_test, y_pred_test)
conf_mx_2 = confusion_matrix(y_test, y_pred_test)
cl_rp_2 = classification_report(y_test, y_pred_test)

print(acc_sc_2)
print(conf_mx_2)
print(cl_rp_2)

0.7467532467532467
[[82 18]
 [21 33]]
              precision    recall  f1-score   support

           0       0.80      0.82      0.81       100
           1       0.65      0.61      0.63        54

    accuracy                           0.75       154
   macro avg       0.72      0.72      0.72       154
weighted avg       0.74      0.75      0.75       154



In [17]:
'meh'

'meh'